### ISSUE TITLE
Large amount of Bitcoin community says Bitcoin.com looks like a scam site

### ISSUE THREAD

**Issue by essofluffy** [bitcoin-portal/bitcoin-portal-content#10]
https://np.reddit.com/r/Bitcoin/comments/3il1qw/new_bitcoincom_design_makes_it_look_like_cheap/

**Comment by essofluffy** [comment]
Looks like a redesign is needed. Who wants to work on this with me?

**Comment by magmahindenburg** [comment]
We are aware of this and have been working on a new version for some time now.
The new version has a complete overhaul using a standard CMS system, therefore, this git repo will be discontinued soon.

**Comment by magmahindenburg** [comment]
A redesign within this git repo would still be within the limits of the fork from bitcoin.com. We aim to create a new original site with original content.

**Comment by essofluffy** [comment]
@magmahindenburg  How can I help out with the new site?

**Comment by bitcoinstore** [comment]
@essofluffy,  we would love your help.
@magmahindenburg, please point him in the right direction with what you need help with.
