### ISSUE TITLE
Homepage Video Error

### ISSUE THREAD

**Issue by sunnankar** [bitcoin-portal/bitcoin-portal-content#6]
It looks like the Watch Video link on the homepage is causing an error.

I think the bug may be in here:

class="pure-button videobutton venobox" data-type="youtube"

**Comment by brettclanton001** [comment]
I don't see a JS error in chrome, and the video is playing fine.  What browser are you using, is this still happening?

**Comment by sunnankar** [comment]
@brettclanton001 Looks like the issue has since been fixed.
